[build]
  # Build command for Slidev
  command = "npm run build"
  # Output directory
  publish = "dist"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Password protection will be configured in Netlify dashboard
# This ensures all routes are protected
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true